# http://travis-ci.org/#!/jupyter-contrib/jupyter_nbextensions_configurator
language: python
sudo: false
addons:
  firefox: latest
dist: trusty
cache: pip
matrix:
    include:
      - os: linux
        python: '3.8'
        env: TOXENV=py38-notebook
install:
    - sudo apt-get update
    - python setup.py install
    - pip install --upgrade pip
    - pip install tox pytest
    - pip install jupyter_nbextensions_configurator

script:
    - tox -e py38

after_success:
    - codecov
